name: Continuous Integration


on:
  pull_request:
    branches:
      - main


permissions:
  contents: read
  pull-requests: write


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ./backend/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: backend
          enable-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./ui/package.json
          cache: npm
          cache-dependency-path: ./ui/package-lock.json

      - uses: hashicorp/setup-terraform@v3

      - name: Python lint check
        working-directory: ./backend/
        run: uvx ruff check

      - name: Python format check
        working-directory: ./backend/
        run: uvx ruff format --check

      - working-directory: ./ui/
        run: npm ci

      - name: Javascript eslint check
        working-directory: ./ui/
        run: npm run lint

      - name: Prettier format check
        working-directory: ./ui/
        run: npm run format

      - run: pip install pre-commit

      - run: pre-commit run --all-files


  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ./backend/.python-version

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: backend
          enable-cache: true

      - uses: actions/setup-node@v4
        with:
          node-version-file: ./ui/package.json
          cache: npm
          cache-dependency-path: ./ui/package-lock.json

      - name: Python unit testing
        working-directory: ./backend/
        run: uv run pytest

      - working-directory: ./ui/
        run: npm ci

      - name: JavaScript unit testing
        working-directory: ./ui/
        run: npm test


  build:
    name: Build
    uses: ./.github/workflows/build.yml
